---
# decreased replica count for CI

searchNodes:
  replicaCount: 3
  image:
    repository: "sonarsource/sonarqube"
    tag: "2026.2.0-master-datacenter-search"
    pullSecrets:
      - name: pullsecret

ApplicationNodes:
  replicaCount: 3
  jwtSecret: "mnGBJtmwRbIREqy3vSw6Cinoi2WEom9JH+iw/tXOJX4="
  image:
    repository: "sonarsource/sonarqube"
    tag: "2026.2.0-master-datacenter-app"
    pullSecrets:
      - name: pullsecret
  webPort: 4023
  cePort: 4024

# Connection to external PostgreSQL
jdbcOverwrite:
  enabled: true
  jdbcUrl: "jdbc:postgresql://external-postgres-postgresql.test.svc.cluster.local:5432/postgres"
  jdbcUsername: "postgres"
  jdbcSecretName: "external-postgres-postgresql"
  jdbcSecretPasswordKey: "postgres-password"

monitoringPasscode: "test"

tests:
  resources:
    requests:
      cpu: 50m
      memory: 200M
      ephemeral-storage: 100M
    limits:
      cpu: 50m
      memory: 200M
      ephemeral-storage: 1000M
