OpenShift:
  enabled: false
  createSCC: false

postgresql:
  enabled: true

searchNodes:
  replicaCount: 1
  image:
    repository: "sonarsource/sonarqube"
    tag: "10.7.0-datacenter-search"
    pullSecrets:
      - name: pullsecret

ApplicationNodes:
  replicaCount: 1
  jwtSecret: "dZ0EB0KxnF++nr5+4vfTCaun/eWbv6gOoXodiAMqcFo="
  image:
    repository: "sonarsource/sonarqube"
    tag: "10.7.0-datacenter-app"
    pullSecrets:
      - name: pullsecret
