apiVersion: v1
name: sonarqube-lts
description: DEPRECATED SonarQube offers Code Quality and Code Security analysis for up to 27 languages. Find Bugs, Vulnerabilities, Security Hotspots and Code Smells throughout your workflow.
version: 2.0.0
appVersion: 8.9.10
# Since SonarQube 9.9 LTS, this chart is no longer maintained. In order to install the new SonarQube 9.9 LTS, please read this https://artifacthub.io/packages/helm/sonarqube/sonarqube#upgrade-from-sonarqube-lts-to-this-chart
deprecated: true
keywords:
  - coverage
  - security
  - code
  - quality
home: https://www.sonarqube.org/
icon: https://www.sonarqube.org/assets/logo-31ad3115b1b4b120f3d1efd63e6b13ac9f1f89437f0cf6881cc4d8b5603a52b4.svg
sources:
  - https://github.com/SonarSource/docker-sonarqube
kubeVersion: ">= 1.19.0-0"
annotations:
  artifacthub.io/changes: |
    - kind: deprecated
      description: "sonarqube-lts chart is no longer maintained, please use the standard sonarqube chart"
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/images: |
    - name: sonarqube
      image: sonarqube:8.9.10-community
