apiVersion: v1
name: sonatype-nexus
version: 5.1.0
appVersion: 3.27.0
description: Sonatype Nexus is an open source repository manager
keywords:
  - artifacts
  - dependency
  - management
  - sonatype
  - nexus
  - repository
home: https://www.sonatype.com/nexus-repository-oss
icon: https://www.sonatype.com/hubfs/2021%20Design%20System/Logo_vert@2x.png
sources:
  - https://github.com/sonatype/nexus-public
  - https://github.com/travelaudience/docker-nexus
  - https://github.com/travelaudience/kubernetes-nexus
  - https://github.com/travelaudience/docker-nexus-backup
  - https://github.com/dbccompany/docker-nexus-backup
maintainers:
  - name: rjkernick
    email: rjkernick@gmail.com
  - name: tsiddique
    email: tsiddique@live.com
