OpenShift:
  enabled: true
  route:
    enabled: true

searchNodes:
  replicaCount: 1
  image:
    repository: "sonarsource/sonarqube"
    tag: "2026.2.0-master-datacenter-search"
    pullSecrets:
      - name: pullsecret

ApplicationNodes:
  replicaCount: 1
  jwtSecret: "dZ0EB0KxnF++nr5+4vfTCaun/eWbv6gOoXodiAMqcFo="
  image:
    repository: "sonarsource/sonarqube"
    tag: "2026.2.0-master-datacenter-app"
    pullSecrets:
      - name: pullsecret

monitoringPasscode: "test"

# Connection to external PostgreSQL
jdbcOverwrite:
  enabled: true
  jdbcUrl: "jdbc:postgresql://external-postgres-postgresql.sonarqube-dce.svc.cluster.local:5432/postgres"
  jdbcUsername: "postgres"
  jdbcSecretName: "external-postgres-postgresql"
  jdbcSecretPasswordKey: "postgres-password"