apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sonarqube.fullname" . }}-init-fs
  labels: {{- include "sonarqube.labels" . | nindent 4 }}
data:
  init_fs.sh: |-
    {{- if .Values.persistence.enabled }}
    chown -R {{ .Values.persistence.uid }}:{{ .Values.persistence.guid }} {{ .Values.sonarqubeFolder }}/data
    chown -R {{ .Values.persistence.uid }}:{{ .Values.persistence.guid }} {{ .Values.sonarqubeFolder }}/temp
    chown -R {{ .Values.persistence.uid }}:{{ .Values.persistence.guid }} {{ .Values.sonarqubeFolder }}/logs
    {{- if .Values.plugins.install }}
    chown -R {{ .Values.persistence.uid }}:{{ .Values.persistence.guid }} {{ .Values.sonarqubeFolder }}/extensions/plugins
    {{- end }}
    {{- if .Values.jdbcOverwrite.oracleJdbcDriverURL }}
    chown -R {{ .Values.persistence.uid }}:{{ .Values.persistence.guid }} {{ .Values.sonarqubeFolder }}/extensions/jdbc-driver/oracle
    {{- end }}
    {{- if .Values.caCerts.enabled }}
    chown -R {{ .Values.persistence.uid }}:{{ .Values.persistence.guid }} {{ .Values.sonarqubeFolder }}/certs
    {{- end }}
    {{- range .Values.persistence.mounts }}
    chown -R {{ $.Values.persistence.uid }}:{{ $.Values.persistence.guid }} {{ .mountPath }}
    {{- end }}
    {{- end }}
