community:
  enabled: true

OpenShift:
  enabled: true
  route:
      enabled: true

image:
  pullSecrets:
    - name: pullsecret
  repository: "sonarsource/sonarqube"
  tag: "25.12.0.117093-master-community"

monitoringPasscode: "test"
