community:
  enabled: true

OpenShift:
  enabled: true
  route:
      enabled: true

postgresql:
  securityContext:
    enabled: false
  containerSecurityContext:
    enabled: false

image:
  pullSecrets:
    - name: pullsecret
  repository: "sonarsource/sonarqube"
  tag: "24.12.0.100206-community"

monitoringPasscode: "test"