community:
  enabled: true

OpenShift:
  enabled: true
  route:
      enabled: true

postgresql:
  securityContext:
    enabled: false
  containerSecurityContext:
    enabled: false

image:
  pullSecrets:
    - name: pullsecret
  repository: "sonarsource/sonarqube"
  tag: "25.11.0.114957-master-community"

monitoringPasscode: "test"