apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sonarqube.fullname" . }}-install-plugins
  labels:
    app: {{ template "sonarqube.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  install_plugins.sh: |-
    {{- if .Values.ApplicationNodes.plugins.install }}
      [ -e {{ .Values.sonarqubeFolder }}/extensions/downloads/* ] && rm {{ .Values.sonarqubeFolder }}/extensions/downloads/*
      cd {{ .Values.sonarqubeFolder }}/extensions/downloads
      {{- range $index, $val := .Values.ApplicationNodes.plugins.install }}
      curl {{ if $.Values.ApplicationNodes.plugins.noCheckCertificate }}--insecure{{ end }} {{ if $.Values.ApplicationNodes.plugins.netrcCreds }}--netrc-file /root/.netrc{{ end }} -fsSLO {{ $val | quote }}
      {{- end }}
    {{- end }}
    {{- if .Values.ApplicationNodes.plugins.lib }}
    {{- range $index, $val := .Values.ApplicationNodes.plugins.lib }}
      cp -f {{ $.Values.sonarqubeFolder }}/extensions/downloads/{{ $val }} {{ $.Values.sonarqubeFolder }}/lib/common/{{ $val }}
    {{- end }}
    {{- end }}
