{{ $applicationNodes := fromYaml (include "applicationNodes" . ) }}
{{ $_ := set .Values "ApplicationNodes" $applicationNodes }}
{{- if or (or .Values.jdbcOverwrite.enabled .Values.jdbcOverwrite.enable) (and .Values.postgresql.service.port .Values.postgresql.postgresqlDatabase) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sonarqube.fullname" . }}-jdbc-config
  labels:
    app: {{ template "sonarqube.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  SONAR_JDBC_USERNAME: {{ template "jdbc.username" . }}
{{- if or .Values.jdbcOverwrite.enabled .Values.jdbcOverwrite.enable }}
  SONAR_JDBC_URL: {{ .Values.jdbcOverwrite.jdbcUrl | trim | quote }}
{{- else if and .Values.postgresql.service.port .Values.postgresql.postgresqlDatabase }}
  SONAR_JDBC_URL: "jdbc:postgresql://{{ template "postgresql.hostname" . }}:{{- .Values.postgresql.service.port -}}/{{- .Values.postgresql.postgresqlDatabase -}}"
{{- end }}
{{- end }}
