apiVersion: v1
kind: Service
metadata:
  name: {{ template "sonarqube.fullname" . }}
  labels:
    app: {{ template "sonarqube.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- range $key, $value := .Values.service.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{ if .Values.service.annotations}}
  annotations:
    {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app: {{ template "sonarqube.name" . }}
    release: {{ .Release.Name }}
  {{- if eq .Values.service.type "LoadBalancer"}}
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- range .Values.service.loadBalancerSourceRanges }}
  - {{ . }}
  {{- end }}
  {{- end -}}
  {{- if .Values.service.loadBalancerIP}}
  loadBalancerIP: {{.Values.service.loadBalancerIP}}
  {{- end }}
  {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "sonarqube.fullname" . }}-headless
  labels:
    app: {{ template "sonarqube.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- range $key, $value := .Values.service.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{ if .Values.service.annotations}}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
    {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
{{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: 9003
      targetPort: hazelcast
      protocol: TCP
      name: hazelcast
  selector:
    app: {{ template "sonarqube.name" . }}
    release: {{ .Release.Name }}


---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "sonarqube.fullname" . }}-search
  labels:
    app: {{ template "sonarqube.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- range $key, $value := .Values.service.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{ if .Values.service.annotations}}
  annotations:
    {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
{{- end }}
spec:
  type: ClusterIP
  ports:
    - port: 9001
      targetPort: search-port
      protocol: TCP
      name: search
    - port: 9002
      targetPort: es-port
      protocol: TCP
      name: es
  selector:
    app: {{ template "sonarqube.name" . }}-search
    release: {{ .Release.Name }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "sonarqube.fullname" . }}-search-headless
  labels:
    app: {{ template "sonarqube.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- range $key, $value := .Values.service.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{ if .Values.service.annotations}}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
    {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
{{- end }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: 9001
      targetPort: search-port
      protocol: TCP
      name: search
    - port: 9002
      targetPort: es-port
      protocol: TCP
      name: es
  selector:
    app: {{ template "sonarqube.name" . }}-search
    release: {{ .Release.Name }}
