dependencies:
  - name: postgresql
    version: 8.1.3
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: postgresql.enabled
  - name: mysql
    version: 1.6.2
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: mysql.enabled
